-- THIS FILE IS ONLY USED FOR LOCAL H2 DB SETUP. FOR A REAL DB, USE FLYWAY.
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (EMAIL VARCHAR PRIMARY KEY, FIRST_NAME VARCHAR NOT NULL, LAST_NAME VARCHAR NULL, AGE INTEGER NULL, GENDER VARCHAR NULL);

INSERT INTO USERS
(EMAIL, FIRST_NAME, LAST_NAME, AGE, GENDER) VALUES
('mike@gmail.com', 'Mike', 'Meyers', 50, 'male'),
('snow@got.us', 'John', 'Snow', 37, 'male'),
('jenni86@mail.com', 'Jennifer', 'Johnson', 20, 'female');
